import React, { useEffect, useState } from 'react';
import { StyleSheet, View, Text, TextInput, TouchableOpacity, ActivityIndicator, PermissionsAndroid, Platform } from 'react-native';
import {
  LiveKitRoom,
  useTracks,
  isTrackReference,
  AudioSession,
  useRoomContext,
} from '@livekit/react-native';
import { Track } from 'livekit-client';
import { SafeAreaProvider, useSafeAreaInsets } from 'react-native-safe-area-context';

// Default URL (can be changed)
const DEFAULT_URL = "wss://vanta-5oidupg1.livekit.cloud";
// Default Token (should be generated by backend)
const DEFAULT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njc4MzgzMzUsImlkZW50aXR5IjoidXNlcjEiLCJpc3MiOiJBUElBS1J2RnZKeHJoQ1ciLCJuYW1lIjoidXNlcjEiLCJuYmYiOjE3Njc3NTE5MzUsInN1YiI6InVzZXIxIiwidmlkZW8iOnsicm9vbSI6InRlc3Qtcm9vbSIsInJvb21Kb2luIjp0cnVlfX0.gxBk28ZrJy1XWZWsaC62dfxIs-k0JrYrQFa9O6-6B5E";

export default function App() {
  const [url, setUrl] = useState(DEFAULT_URL);
  const [token, setToken] = useState(DEFAULT_TOKEN);
  const [shouldConnect, setShouldConnect] = useState(false);

  useEffect(() => {
    // Configure Audio Session for Voice Communication
    AudioSession.startAudioSession();
    return () => {
      AudioSession.stopAudioSession();
    };
  }, []);

  const handleConnect = async () => {
    if (Platform.OS === 'android') {
      try {
        await PermissionsAndroid.requestMultiple([
          PermissionsAndroid.PERMISSIONS.CAMERA,
          PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        ]);
      } catch (err) {
        console.warn('Failed to request permissions:', err);
      }
    }
    setShouldConnect(true);
  };

  const handleDisconnect = () => {
    setShouldConnect(false);
  };

  return (
    <SafeAreaProvider>
      <View style={styles.container}>
        {!shouldConnect ? (
          <ConnectionScreen
            url={url}
            setUrl={setUrl}
            token={token}
            setToken={setToken}
            onConnect={handleConnect}
          />
        ) : (
          <LiveKitRoom
            serverUrl={url}
            token={token}
            connect={true}
            options={{
              adaptiveStream: true,
              publishDefaults: {
                audioPreset: { maxBitrate: 32000 },
              }
            }}
            audio={true} // Enable Mic
            video={false} // Disable Camera for now (Voice Mode)
            onDisconnected={handleDisconnect}
            style={styles.room}
          >
            <RoomContent />
          </LiveKitRoom>
        )}
      </View>
    </SafeAreaProvider>
  );
}

function ConnectionScreen({ url, setUrl, token, setToken, onConnect }: any) {
  const insets = useSafeAreaInsets();
  return (
    <View style={[styles.connectContainer, { paddingTop: insets.top }]}>
      <Text style={styles.title}>Vanta</Text>
      <Text style={styles.subtitle}>Gemini Live Assistant</Text>

      <TextInput
        style={styles.input}
        placeholder="LiveKit URL (wss://...)"
        placeholderTextColor="#666"
        value={url}
        onChangeText={setUrl}
        autoCapitalize="none"
      />

      <TextInput
        style={styles.input}
        placeholder="Access Token"
        placeholderTextColor="#666"
        value={token}
        onChangeText={setToken}
        autoCapitalize="none"
      />

      <TouchableOpacity style={styles.button} onPress={onConnect}>
        <Text style={styles.buttonText}>Connect</Text>
      </TouchableOpacity>
    </View>
  );
}

function RoomContent() {
  const room = useRoomContext();
  const [isMuted, setIsMuted] = useState(false);

  // Clean up visualization or other room logic here

  const toggleMic = () => {
    if (room?.localParticipant) {
      const enabled = !room.localParticipant.isMicrophoneEnabled;
      room.localParticipant.setMicrophoneEnabled(enabled);
      setIsMuted(!enabled);
    }
  };

  return (
    <View style={styles.roomContainer}>
      {/* Audio Playback is handled by LiveKit Native SDK automatically when subscribed */}


      <View style={styles.visualizerContainer}>
        <Text style={styles.statusText}>Connecting to Agent</Text>
        {/* Visualizer would go here */}
        <ActivityIndicator size="large" color="#00ff00" />
      </View>

      <View style={styles.controls}>
        <TouchableOpacity style={[styles.controlButton, isMuted && styles.mutedButton]} onPress={toggleMic}>
          <Text style={styles.controlText}>{isMuted ? "Unmute" : "Mute"}</Text>
        </TouchableOpacity>

        <TouchableOpacity style={[styles.controlButton, styles.disconnectButton]} onPress={() => room?.disconnect()}>
          <Text style={styles.controlText}>Disconnect</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  connectContainer: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
  },
  room: {
    flex: 1,
  },
  roomContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: '#aaa',
    marginBottom: 48,
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#222',
    color: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    fontSize: 16,
  },
  button: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 16,
  },
  buttonText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  statusText: {
    color: '#fff',
    fontSize: 24,
    marginBottom: 24,
  },
  visualizerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  controls: {
    flexDirection: 'row',
    marginBottom: 48,
    gap: 24,
  },
  controlButton: {
    backgroundColor: '#222',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 30,
  },
  mutedButton: {
    backgroundColor: '#500',
  },
  disconnectButton: {
    backgroundColor: '#d00',
  },
  controlText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
